<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('districts')->insert(['StCode' => 32,'DistrictName' => 'Adilabad', 'DistCode' => 1]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Agra', 'DistCode' => 2]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Ahmed Nagar', 'DistCode'=> 3]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Ahmedabad City', 'DistCode'=> 4]) ;
        DB::table('districts')->insert(['StCode' => 24,'DistrictName' => 'Aizawl','DistCode' => 5]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Ajmer','DistCode' => 6]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Akola','DistCode' => 7]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Aligarh','DistCode' => 8]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Allahabad','DistCode' => 9]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Alleppey','DistCode' => 10]) ;
        DB::table('districts')->insert(['StCode' => 35,'DistrictName' => 'Almora','DistCode' => 11]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Alwar','DistCode' => 12]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Alwaye','DistCode' => 13]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Amalapuram','DistCode' => 14]) ;
        DB::table('districts')->insert(['StCode' => 13,'DistrictName' => 'Ambala','DistCode' => 15]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Ambedkar Nagar','DistCode' => 16]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Amravati','DistCode' => 17]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Amreli','DistCode' => 18]) ;
        DB::table('districts')->insert(['StCode' => 28,'DistrictName' => 'Amritsar','DistCode' => 19]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Anakapalle','DistCode' => 20]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Anand','DistCode' => 21]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Anantapur','DistCode' => 22]) ;
        DB::table('districts')->insert(['StCode' => 15,'DistrictName' => 'Ananthnag','DistCode' => 23]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Anna Road H.O','DistCode' => 24]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Arakkonam','DistCode' => 25]) ;
        DB::table('districts')->insert(['StCode' => 36,'DistrictName' => 'Asansol','DistCode' => 26]) ;
        DB::table('districts')->insert(['StCode' => 26,'DistrictName' => 'Aska','DistCode' => 27]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Auraiya','DistCode' => 28]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Aurangabad','DistCode' => 29]) ;
        DB::table('districts')->insert(['StCode' => 5,'DistrictName' => 'AurangabadBihar','DistCode' => 30]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Azamgarh','DistCode' => 31]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Bagalkot','DistCode' => 32]) ;
        DB::table('districts')->insert(['StCode' => 35,'DistrictName' => 'Bageshwar','DistCode' => 33]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Bagpat','DistCode' => 34]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Bahraich','DistCode' => 35]) ;
        DB::table('districts')->insert(['StCode' => 20,'DistrictName' => 'Balaghat','DistCode' => 36]) ;
        DB::table('districts')->insert(['StCode' => 26,'DistrictName' => 'Balangir','DistCode' => 37]) ;
        DB::table('districts')->insert(['StCode' => 26,'DistrictName' => 'Balasore','DistCode' => 38]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Ballia','DistCode' => 39]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Balrampur','DistCode' => 40]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Banasanktha','DistCode' => 41]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Banda','DistCode' => 42]) ;
        DB::table('districts')->insert(['StCode' => 15,'DistrictName' => 'Bandipur','DistCode' => 43]) ;
        DB::table('districts')->insert(['StCode' => 36,'DistrictName' => 'Bankura','DistCode' => 44]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Banswara','DistCode' => 45]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Barabanki','DistCode' => 46]) ;
        DB::table('districts')->insert(['StCode' => 15,'DistrictName' => 'Baramulla','DistCode' => 47]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Baran','DistCode' => 48]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Bardoli','DistCode' => 49]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Bareilly','DistCode' => 50]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Barmer','DistCode' => 51]) ;
        DB::table('districts')->insert(['StCode' => 28,'DistrictName' => 'Barnala','DistCode' => 52]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'Barpeta','DistCode' => 53]) ;
        DB::table('districts')->insert(['StCode' => 7,'DistrictName' => 'Bastar','DistCode' => 54]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Basti','DistCode' => 55]) ;
        DB::table('districts')->insert(['StCode' => 28,'DistrictName' => 'Bathinda','DistCode' => 56]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Beed','DistCode' => 57]) ;
        DB::table('districts')->insert(['StCode' => 5,'DistrictName' => 'Begusarai','DistCode' => 58]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Belgaum','DistCode' => 59]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Bellary','DistCode' => 60]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Bengaluru East','DistCode' => 61]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Bengaluru South','DistCode' => 62]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Bengaluru West','DistCode' => 63]) ;
        DB::table('districts')->insert(['StCode' => 26,'DistrictName' => 'Berhampur','DistCode' => 64]) ;
        DB::table('districts')->insert(['StCode' => 26,'DistrictName' => 'Bhadrak','DistCode' => 65]) ;
        DB::table('districts')->insert(['StCode' => 5,'DistrictName' => 'Bhagalpur','DistCode' => 66]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Bhandara','DistCode' => 67]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Bharatpur','DistCode' => 68]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Bharuch','DistCode' => 69]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Bhavnagar','DistCode' => 70]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Bhilwara','DistCode' => 71]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Bhimavaram','DistCode' => 72]) ;
        DB::table('districts')->insert(['StCode' => 13,'DistrictName' => 'Bhiwani','DistCode' => 73]) ;
        DB::table('districts')->insert(['StCode' => 5,'DistrictName' => 'Bhojpur','DistCode' => 74]) ;
        DB::table('districts')->insert(['StCode' => 20,'DistrictName' => 'Bhopal','DistCode' => 75]) ;
        DB::table('districts')->insert(['StCode' => 26,'DistrictName' => 'Bhubaneswar','DistCode' => 76]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Bidar','DistCode' => 77]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Bijapur','DistCode' => 78]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Bijnor','DistCode' => 79]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Bikaner','DistCode' => 80]) ;
        DB::table('districts')->insert(['StCode' => 7,'DistrictName' => 'Bilaspur','DistCode' => 81]) ;
        DB::table('districts')->insert(['StCode' => 36,'DistrictName' => 'Birbhum','DistCode' => 82]) ;
        DB::table('districts')->insert(['StCode' => 22,'DistrictName' => 'Bishnupur','DistCode' => 83]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'Bongaigaon','DistCode' => 84]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Budaun','DistCode' => 85]) ;
        DB::table('districts')->insert(['StCode' => 15,'DistrictName' => 'Budgam','DistCode' => 86]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Bulandshahr','DistCode' => 87]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Buldhana','DistCode' => 88]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Bundi','DistCode' => 89]) ;
        DB::table('districts')->insert(['StCode' => 36,'DistrictName' => 'Burdwan','DistCode' => 90]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'Cachar','DistCode' => 91]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Calicut','DistCode' => 92]) ;
        DB::table('districts')->insert(['StCode' => 1,'DistrictName' => 'Carnicobar','DistCode' => 93]) ;
        DB::table('districts')->insert(['StCode' => 14,'DistrictName' => 'Chamba','DistCode' => 94]) ;
        DB::table('districts')->insert(['StCode' => 35,'DistrictName' => 'Chamoli','DistCode' => 95]) ;
        DB::table('districts')->insert(['StCode' => 35,'DistrictName' => 'Champawat','DistCode' => 96]) ;
        DB::table('districts')->insert(['StCode' => 24,'DistrictName' => 'Champhai','DistCode' => 97]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Chandauli','DistCode' => 98]) ;
        DB::table('districts')->insert(['StCode' => 22,'DistrictName' => 'Chandel','DistCode' => 99]) ;
        DB::table('districts')->insert(['StCode' => 6,'DistrictName' => 'Chandigarh','DistCode' => 100]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Chandrapur','DistCode' => 101]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Changanacherry','DistCode' => 102]) ;
        DB::table('districts')->insert(['StCode' => 3,'DistrictName' => 'Changlang','DistCode' => 103]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Channapatna','DistCode' => 104]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Chengalpattu','DistCode' => 105]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Chennai City Central','DistCode' => 106]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Chennai City North','DistCode' => 107]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Chennai City South','DistCode' => 108]) ;
        DB::table('districts')->insert(['StCode' => 20,'DistrictName' => 'Chhatarpur','DistCode' => 109]) ;
        DB::table('districts')->insert(['StCode' => 20,'DistrictName' => 'Chhindwara','DistCode' => 110]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Chikmagalur','DistCode' => 111]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Chikodi','DistCode' => 112]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Chitradurga','DistCode' => 113]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Chitrakoot','DistCode' => 114]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Chittoor','DistCode' => 115]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Chittorgarh','DistCode' => 116]) ;
        DB::table('districts')->insert(['StCode' => 22,'DistrictName' => 'Churachandpur','DistCode' => 117]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Churu','DistCode' => 118]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Coimbatore','DistCode' => 119]) ;
        DB::table('districts')->insert(['StCode' => 36,'DistrictName' => 'Contai','DistCode' => 120]) ;
        DB::table('districts')->insert(['StCode' => 36,'DistrictName' => 'Cooch Behar','DistCode' => 121]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Cuddalore','DistCode' => 122]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Cuddapah','DistCode' => 123]) ;
        DB::table('districts')->insert(['StCode' => 26,'DistrictName' => 'Cuttack City','DistCode' => 124]) ;
        DB::table('districts')->insert(['StCode' => 26,'DistrictName' => 'Cuttack North','DistCode' => 125]) ;
        DB::table('districts')->insert(['StCode' => 26,'DistrictName' => 'Cuttack South','DistCode' => 126]) ;
        DB::table('districts')->insert(['StCode' => 8,'DistrictName' => 'Dadra & Nagar Haveli','DistCode' => 127]) ;
        DB::table('districts')->insert(['StCode' => 9,'DistrictName' => 'Daman','DistCode' => 128]) ;
        DB::table('districts')->insert(['StCode' => 5,'DistrictName' => 'Darbhanga','DistCode' => 129]) ;
        DB::table('districts')->insert(['StCode' => 36,'DistrictName' => 'Darjiling','DistCode' => 130]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'Darrang','DistCode' => 131]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Dausa','DistCode' => 132]) ;
        DB::table('districts')->insert(['StCode' => 14,'DistrictName' => 'Dehra Gopipur','DistCode' => 133]) ;
        DB::table('districts')->insert(['StCode' => 35,'DistrictName' => 'Dehradun','DistCode' => 134]) ;
        DB::table('districts')->insert(['StCode' => 10,'DistrictName' => 'Delhi','DistCode' => 135]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Deoria','DistCode' => 136]) ;
        DB::table('districts')->insert(['StCode' => 33,'DistrictName' => 'Dhalai','DistCode' => 137]) ;
        DB::table('districts')->insert(['StCode' => 16,'DistrictName' => 'Dhanbad','DistCode' => 138]) ;
        DB::table('districts')->insert(['StCode' => 14,'DistrictName' => 'Dharamsala','DistCode' => 139]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Dharmapuri','DistCode' => 140]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Dharwad','DistCode' => 141]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'Dhemaji','DistCode' => 142]) ;
        DB::table('districts')->insert(['StCode' => 26,'DistrictName' => 'Dhenkanal','DistCode' => 143]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Dholpur','DistCode' => 144]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'Dhubri','DistCode' => 145]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Dhule','DistCode' => 146]) ;
        DB::table('districts')->insert(['StCode' => 3,'DistrictName' => 'Dibang Valley','DistCode' => 147]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'Dibrugarh','DistCode' => 148]) ;
        DB::table('districts')->insert(['StCode' => 1,'DistrictName' => 'Diglipur','DistCode' => 149]) ;
        DB::table('districts')->insert(['StCode' => 25,'DistrictName' => 'Dimapur','DistCode' => 150]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Dindigul','DistCode' => 151]) ;
        DB::table('districts')->insert(['StCode' => 9,'DistrictName' => 'Diu','DistCode' => 152]) ;
        DB::table('districts')->insert(['StCode' => 15,'DistrictName' => 'Doda','DistCode' => 153]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Dungarpur','DistCode' => 154]) ;
        DB::table('districts')->insert(['StCode' => 7,'DistrictName' => 'Durg','DistCode' => 155]) ;
        DB::table('districts')->insert(['StCode' => 5,'DistrictName' => 'East Champaran','DistCode' => 156]) ;
        DB::table('districts')->insert(['StCode' => 23,'DistrictName' => 'East Garo Hills','DistCode' => 157]) ;
        DB::table('districts')->insert(['StCode' => 3,'DistrictName' => 'East Kameng','DistCode' => 158]) ;
        DB::table('districts')->insert(['StCode' => 23,'DistrictName' => 'East Khasi Hills','DistCode' => 159]) ;
        DB::table('districts')->insert(['StCode' => 3,'DistrictName' => 'East Siang','DistCode' => 160]) ;
        DB::table('districts')->insert(['StCode' => 30,'DistrictName' => 'East Sikkim','DistCode' => 161]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Eluru','DistCode' => 162]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Ernakulam','DistCode' => 163]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Erode','DistCode' => 164]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Etah','DistCode' => 165]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Etawah','DistCode' => 166]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Faizabad','DistCode' => 167]) ;
        DB::table('districts')->insert(['StCode' => 13,'DistrictName' => 'Faridabad','DistCode' => 168]) ;
        DB::table('districts')->insert(['StCode' => 28,'DistrictName' => 'Faridkot','DistCode' => 169]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Farrukhabad','DistCode' => 170]) ;
        DB::table('districts')->insert(['StCode' => 28,'DistrictName' => 'Fatehgarh Sahib','DistCode' => 171]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Fatehpur','DistCode' => 172]) ;
        DB::table('districts')->insert(['StCode' => 28,'DistrictName' => 'Fazilka','DistCode' => 173]) ;
        DB::table('districts')->insert(['StCode' => 1,'DistrictName' => 'Ferrargunj','DistCode' => 174]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Firozabad','DistCode' => 175]) ;
        DB::table('districts')->insert(['StCode' => 28,'DistrictName' => 'Firozpur','DistCode' => 176]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Gadag','DistCode' => 177]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Gadchiroli','DistCode' => 178]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Gandhinagar','DistCode' => 179]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Ganganagar','DistCode' => 180]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Gautam Buddha Nagar','DistCode' => 181]) ;
        DB::table('districts')->insert(['StCode' => 5,'DistrictName' => 'Gaya','DistCode' => 182]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Ghaziabad','DistCode' => 183]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Ghazipur','DistCode' => 184]) ;
        DB::table('districts')->insert(['StCode' => 16,'DistrictName' => 'Giridih','DistCode' => 185]) ;
        DB::table('districts')->insert(['StCode' => 11,'DistrictName' => 'Goa','DistCode' => 186]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'Goalpara','DistCode' => 187]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Gokak','DistCode' => 188]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'Golaghat','DistCode' => 189]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Gonda','DistCode' => 190]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Gondal','DistCode' => 191]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Gondia','DistCode' => 192]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Gorakhpur','DistCode' => 193]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Gudivada','DistCode' => 194]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Gudur','DistCode' => 195]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Gulbarga','DistCode' => 196]) ;
        DB::table('districts')->insert(['StCode' => 20,'DistrictName' => 'Guna','DistCode' => 197]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Guntur','DistCode' => 198]) ;
        DB::table('districts')->insert(['StCode' => 28,'DistrictName' => 'Gurdaspur','DistCode' => 199]) ;
        DB::table('districts')->insert(['StCode' => 13,'DistrictName' => 'Gurugram','DistCode' => 200]) ;
        DB::table('districts')->insert(['StCode' => 20,'DistrictName' => 'Gwalior','DistCode' => 201]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'Hailakandi','DistCode' => 202]) ;
        DB::table('districts')->insert(['StCode' => 14,'DistrictName' => 'Hamirpur HP','DistCode' => 203]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Hamirpur UP','DistCode' => 204]) ;
        DB::table('districts')->insert(['StCode' => 32,'DistrictName' => 'Hanamkonda','DistCode' => 205]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Hanumangarh','DistCode' => 206]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Hardoi','DistCode' => 207]) ;
        DB::table('districts')->insert(['StCode' => 35,'DistrictName' => 'Haridwar','DistCode' => 208]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Hassan','DistCode' => 209]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Hathras','DistCode' => 210]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Haveri','DistCode' => 211]) ;
        DB::table('districts')->insert(['StCode' => 16,'DistrictName' => 'Hazaribagh','DistCode' => 212]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Hindupur','DistCode' => 213]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Hingoli','DistCode' => 214]) ;
        DB::table('districts')->insert(['StCode' => 13,'DistrictName' => 'Hissar','DistCode' => 215]) ;
        DB::table('districts')->insert(['StCode' => 36,'DistrictName' => 'Hooghly','DistCode' => 216]) ;
        DB::table('districts')->insert(['StCode' => 20,'DistrictName' => 'Hoshangabad','DistCode' => 217]) ;
        DB::table('districts')->insert(['StCode' => 28,'DistrictName' => 'Hoshiarpur','DistCode' => 218]) ;
        DB::table('districts')->insert(['StCode' => 36,'DistrictName' => 'Howrah','DistCode' => 219]) ;
        DB::table('districts')->insert(['StCode' => 1,'DistrictName' => 'Hut Bay','DistCode' => 220]) ;
        DB::table('districts')->insert(['StCode' => 32,'DistrictName' => 'Hyderabad City','DistCode' => 221]) ;
        DB::table('districts')->insert(['StCode' => 32,'DistrictName' => 'Hyderabad SouthEast','DistCode' => 222]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Idukki','DistCode' => 223]) ;
        DB::table('districts')->insert(['StCode' => 22,'DistrictName' => 'Imphal East','DistCode' => 224]) ;
        DB::table('districts')->insert(['StCode' => 22,'DistrictName' => 'Imphal West','DistCode' => 225]) ;
        DB::table('districts')->insert(['StCode' => 20,'DistrictName' => 'Indore City','DistCode' => 226]) ;
        DB::table('districts')->insert(['StCode' => 20,'DistrictName' => 'Indore Moffusil','DistCode' => 227]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Irinjalakuda','DistCode' => 228]) ;
        DB::table('districts')->insert(['StCode' => 20,'DistrictName' => 'Jabalpur','DistCode' => 229]) ;
        DB::table('districts')->insert(['StCode' => 23,'DistrictName' => 'Jaintia Hills','DistCode' => 230]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Jaipur','DistCode' => 231]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Jaisalmer','DistCode' => 232]) ;
        DB::table('districts')->insert(['StCode' => 28,'DistrictName' => 'Jalandhar','DistCode' => 233]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Jalaun','DistCode' => 234]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Jalgaon','DistCode' => 235]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Jalna','DistCode' => 236]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Jalor','DistCode' => 237]) ;
        DB::table('districts')->insert(['StCode' => 36,'DistrictName' => 'Jalpaiguri','DistCode' => 238]) ;
        DB::table('districts')->insert(['StCode' => 15,'DistrictName' => 'Jammu','DistCode' => 239]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Jamnagar','DistCode' => 240]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Jaunpur','DistCode' => 241]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Jhalawar','DistCode' => 242]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Jhansi','DistCode' => 243]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Jhujhunu','DistCode' => 244]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Jodhpur','DistCode' => 245]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'Jorhat','DistCode' => 246]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Junagadh','DistCode' => 247]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Jyotiba Phule Nagar','DistCode' => 248]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Kakinada','DistCode' => 249]) ;
        DB::table('districts')->insert(['StCode' => 26,'DistrictName' => 'Kalahandi','DistCode' => 250]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'Kamrup','DistCode' => 251]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Kanchipuram','DistCode' => 252]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Kannauj','DistCode' => 253]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Kanniyakumari','DistCode' => 254]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Kannur','DistCode' => 255]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Kanpur Dehat','DistCode' => 256]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Kanpur Nagar','DistCode' => 257]) ;
        DB::table('districts')->insert(['StCode' => 28,'DistrictName' => 'Kapurthala','DistCode' => 258]) ;
        DB::table('districts')->insert(['StCode' => 27,'DistrictName' => 'Karaikal','DistCode' => 259]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Karaikudi','DistCode' => 260]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Karauli','DistCode' => 261]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'Karbi Anglong','DistCode' => 262]) ;
        DB::table('districts')->insert(['StCode' => 15,'DistrictName' => 'Kargil','DistCode' => 263]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'Karimganj','DistCode' => 264]) ;
        DB::table('districts')->insert(['StCode' => 32,'DistrictName' => 'Karimnagar','DistCode' => 265]) ;
        DB::table('districts')->insert(['StCode' => 13,'DistrictName' => 'Karnal','DistCode' => 266]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Karur','DistCode' => 267]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Karwar','DistCode' => 268]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Kasaragod','DistCode' => 269]) ;
        DB::table('districts')->insert(['StCode' => 15,'DistrictName' => 'Kathua','DistCode' => 270]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Kaushambi','DistCode' => 271]) ;
        DB::table('districts')->insert(['StCode' => 26,'DistrictName' => 'Keonjhar','DistCode' => 272]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Khammam AP','DistCode' => 273]) ;
        DB::table('districts')->insert(['StCode' => 32,'DistrictName' => 'Khammam TL','DistCode' => 274]) ;
        DB::table('districts')->insert(['StCode' => 20,'DistrictName' => 'Khandwa','DistCode' => 275]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Kheda','DistCode' => 276]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Kheri','DistCode' => 277]) ;
        DB::table('districts')->insert(['StCode' => 25,'DistrictName' => 'Kiphire','DistCode' => 278]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Kodagu','DistCode' => 279]) ;
        DB::table('districts')->insert(['StCode' => 25,'DistrictName' => 'Kohima','DistCode' => 280]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'Kokrajhar','DistCode' => 281]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Kolar','DistCode' => 282]) ;
        DB::table('districts')->insert(['StCode' => 24,'DistrictName' => 'Kolasib','DistCode' => 283]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Kolhapur','DistCode' => 284]) ;
        DB::table('districts')->insert(['StCode' => 36,'DistrictName' => 'Kolkata','DistCode' => 285]) ;
        DB::table('districts')->insert(['StCode' => 26,'DistrictName' => 'Koraput','DistCode' => 286]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Kota','DistCode' => 287]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Kottayam','DistCode' => 288]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Kovilpatti','DistCode' => 289]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Krishnagiri','DistCode' => 290]) ;
        DB::table('districts')->insert(['StCode' => 15,'DistrictName' => 'Kulgam','DistCode' => 291]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Kumbakonam','DistCode' => 292]) ;
        DB::table('districts')->insert(['StCode' => 15,'DistrictName' => 'Kupwara','DistCode' => 293]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Kurnool','DistCode' => 294]) ;
        DB::table('districts')->insert(['StCode' => 13,'DistrictName' => 'Kurukshetra','DistCode' => 295]) ;
        DB::table('districts')->insert(['StCode' => 3,'DistrictName' => 'Kurung Kumey','DistCode' => 296]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Kushinagar','DistCode' => 297]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Kutch','DistCode' => 298]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'Lakhimpur','DistCode' => 299]) ;
        DB::table('districts')->insert(['StCode' => 19,'DistrictName' => 'Lakshadweep','DistCode' => 300]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Lalitpur','DistCode' => 301]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Latur','DistCode' => 302]) ;
        DB::table('districts')->insert(['StCode' => 24,'DistrictName' => 'Lawngtlai','DistCode' => 303]) ;
        DB::table('districts')->insert(['StCode' => 15,'DistrictName' => 'Leh','DistCode' => 304]) ;
        DB::table('districts')->insert(['StCode' => 3,'DistrictName' => 'Lohit','DistCode' => 305]) ;
        DB::table('districts')->insert(['StCode' => 25,'DistrictName' => 'Longleng','DistCode' => 306]) ;
        DB::table('districts')->insert(['StCode' => 3,'DistrictName' => 'Lower Subansiri','DistCode' => 307]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Lucknow','DistCode' => 308]) ;
        DB::table('districts')->insert(['StCode' => 28,'DistrictName' => 'Ludhiana','DistCode' => 309]) ;
        DB::table('districts')->insert(['StCode' => 24,'DistrictName' => 'Lunglei','DistCode' => 310]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Machilipatnam','DistCode' => 311]) ;
        DB::table('districts')->insert(['StCode' => 5,'DistrictName' => 'Madhubani','DistCode' => 312]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Madurai','DistCode' => 313]) ;
        DB::table('districts')->insert(['StCode' => 32,'DistrictName' => 'Mahabubnagar','DistCode' => 314]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Maharajganj','DistCode' => 315]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Mahesana','DistCode' => 316]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Mahoba','DistCode' => 317]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Mainpuri','DistCode' => 318]) ;
        DB::table('districts')->insert(['StCode' => 36,'DistrictName' => 'Malda','DistCode' => 319]) ;
        DB::table('districts')->insert(['StCode' => 24,'DistrictName' => 'Mammit','DistCode' => 320]) ;
        DB::table('districts')->insert(['StCode' => 14,'DistrictName' => 'Mandi','DistCode' => 321]) ;
        DB::table('districts')->insert(['StCode' => 20,'DistrictName' => 'Mandsaur','DistCode' => 322]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Mandya','DistCode' => 323]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Mangalore','DistCode' => 324]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Manjeri','DistCode' => 325]) ;
        DB::table('districts')->insert(['StCode' => 28,'DistrictName' => 'Mansa','DistCode' => 326]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'Marigaon','DistCode' => 327]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Mathura','DistCode' => 328]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Mau','DistCode' => 329]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Mavelikara','DistCode' => 330]) ;
        DB::table('districts')->insert(['StCode' => 1,'DistrictName' => 'Mayabander','DistCode' => 331]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Mayiladuthurai','DistCode' => 332]) ;
        DB::table('districts')->insert(['StCode' => 26,'DistrictName' => 'Mayurbhanj','DistCode' => 333]) ;
        DB::table('districts')->insert(['StCode' => 32,'DistrictName' => 'Medak','DistCode' => 334]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Meerut','DistCode' => 335]) ;
        DB::table('districts')->insert(['StCode' => 23,'DistrictName' => 'Meghalaya','DistCode' => 336]) ;
        DB::table('districts')->insert(['StCode' => 36,'DistrictName' => 'Midnapore','DistCode' => 337]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Mirzapur','DistCode' => 338]) ;
        DB::table('districts')->insert(['StCode' => 28,'DistrictName' => 'Moga','DistCode' => 339]) ;
        DB::table('districts')->insert(['StCode' => 28,'DistrictName' => 'Mohali','DistCode' => 340]) ;
        DB::table('districts')->insert(['StCode' => 25,'DistrictName' => 'Mokokchung','DistCode' => 341]) ;
        DB::table('districts')->insert(['StCode' => 25,'DistrictName' => 'Mon','DistCode' => 342]) ;
        DB::table('districts')->insert(['StCode' => 5,'DistrictName' => 'Monghyr','DistCode' => 343]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Moradabad','DistCode' => 344]) ;
        DB::table('districts')->insert(['StCode' => 20,'DistrictName' => 'Morena','DistCode' => 345]) ;
        DB::table('districts')->insert(['StCode' => 28,'DistrictName' => 'Muktsar','DistCode' => 346]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Mumbai','DistCode' => 347]) ;
        DB::table('districts')->insert(['StCode' => 36,'DistrictName' => 'Murshidabad','DistCode' => 348]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Muzaffarnagar','DistCode' => 349]) ;
        DB::table('districts')->insert(['StCode' => 5,'DistrictName' => 'Muzaffarpur','DistCode' => 350]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Mysore','DistCode' => 351]) ;
        DB::table('districts')->insert(['StCode' => 36,'DistrictName' => 'Nadia','DistCode' => 352]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'Nagaon','DistCode' => 353]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Nagapattinam','DistCode' => 354]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Nagaur','DistCode' => 355]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Nagpur','DistCode' => 356]) ;
        DB::table('districts')->insert(['StCode' => 35,'DistrictName' => 'Nainital','DistCode' => 357]) ;
        DB::table('districts')->insert(['StCode' => 5,'DistrictName' => 'Nalanda','DistCode' => 358]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'Nalbari','DistCode' => 359]) ;
        DB::table('districts')->insert(['StCode' => 32,'DistrictName' => 'Nalgonda','DistCode' => 360]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Namakkal','DistCode' => 361]) ;
        DB::table('districts')->insert(['StCode' => 1,'DistrictName' => 'Nancorie','DistCode' => 362]) ;
        DB::table('districts')->insert(['StCode' => 1,'DistrictName' => 'Nancowrie','DistCode' => 363]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Nanded','DistCode' => 364]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Nandurbar','DistCode' => 365]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Nandyal','DistCode' => 366]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Nanjangud','DistCode' => 367]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Narasaraopet','DistCode' => 368]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Nashik','DistCode' => 369]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Navsari','DistCode' => 370]) ;
        DB::table('districts')->insert(['StCode' => 5,'DistrictName' => 'Nawadha','DistCode' => 371]) ;
        DB::table('districts')->insert(['StCode' => 28,'DistrictName' => 'Nawanshahr','DistCode' => 372]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Nellore','DistCode' => 373]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Nilgiris','DistCode' => 374]) ;
        DB::table('districts')->insert(['StCode' => 32,'DistrictName' => 'Nizamabad','DistCode' => 375]) ;
        DB::table('districts')->insert(['StCode' => 36,'DistrictName' => 'North 24 Parganas','DistCode' => 376]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'North Cachar Hills','DistCode' => 377]) ;
        DB::table('districts')->insert(['StCode' => 36,'DistrictName' => 'North Dinajpur','DistCode' => 378]) ;
        DB::table('districts')->insert(['StCode' => 30,'DistrictName' => 'North Sikkim','DistCode' => 379]) ;
        DB::table('districts')->insert(['StCode' => 33,'DistrictName' => 'North Tripura','DistCode' => 380]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Osmanabad','DistCode' => 381]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Ottapalam','DistCode' => 382]) ;
        DB::table('districts')->insert(['StCode' => 16,'DistrictName' => 'Palamau','DistCode' => 383]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Palghat','DistCode' => 384]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Pali','DistCode' => 385]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Panchmahals','DistCode' => 386]) ;
        DB::table('districts')->insert(['StCode' => 3,'DistrictName' => 'Papum Pare','DistCode' => 387]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Parbhani','DistCode' => 388]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Parvathipuram','DistCode' => 389]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Patan','DistCode' => 390]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Pathanamthitta','DistCode' => 391]) ;
        DB::table('districts')->insert(['StCode' => 28,'DistrictName' => 'Patiala','DistCode' => 392]) ;
        DB::table('districts')->insert(['StCode' => 5,'DistrictName' => 'Patna','DistCode' => 393]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Pattukottai','DistCode' => 394]) ;
        DB::table('districts')->insert(['StCode' => 35,'DistrictName' => 'Pauri Garhwal','DistCode' => 395]) ;
        DB::table('districts')->insert(['StCode' => 32,'DistrictName' => 'Peddapalli','DistCode' => 396]) ;
        DB::table('districts')->insert(['StCode' => 25,'DistrictName' => 'Peren','DistCode' => 397]) ;
        DB::table('districts')->insert(['StCode' => 25,'DistrictName' => 'Phek','DistCode' => 398]) ;
        DB::table('districts')->insert(['StCode' => 26,'DistrictName' => 'Phulbani','DistCode' => 399]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Pilibhit','DistCode' => 400]) ;
        DB::table('districts')->insert(['StCode' => 35,'DistrictName' => 'Pithoragarh','DistCode' => 401]) ;
        DB::table('districts')->insert(['StCode' => 27,'DistrictName' => 'Poducherry PD','DistCode' => 402]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Poducherry TN','DistCode' => 403]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Pollachi','DistCode' => 404]) ;
        DB::table('districts')->insert(['StCode' => 15,'DistrictName' => 'Poonch','DistCode' => 405]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Porbandar','DistCode' => 406]) ;
        DB::table('districts')->insert(['StCode' => 1,'DistrictName' => 'Port Blair','DistCode' => 407]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Prakasam','DistCode' => 408]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Pratapgarh','DistCode' => 409]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Proddatur','DistCode' => 410]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Pudukkottai','DistCode' => 411]) ;
        DB::table('districts')->insert(['StCode' => 15,'DistrictName' => 'Pulwama','DistCode' => 412]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Pune','DistCode' => 413]) ;
        DB::table('districts')->insert(['StCode' => 26,'DistrictName' => 'Puri','DistCode' => 414]) ;
        DB::table('districts')->insert(['StCode' => 5,'DistrictName' => 'Purnea','DistCode' => 415]) ;
        DB::table('districts')->insert(['StCode' => 36,'DistrictName' => 'Purulia','DistCode' => 416]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Puttur','DistCode' => 417]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Quilon','DistCode' => 418]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Raebareli','DistCode' => 419]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Raichur','DistCode' => 420]) ;
        DB::table('districts')->insert(['StCode' => 7,'DistrictName' => 'Raigarh CT','DistCode' => 421]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Raigarh MH','DistCode' => 422]) ;
        DB::table('districts')->insert(['StCode' => 7,'DistrictName' => 'Raipur','DistCode' => 423]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Rajahmundry','DistCode' => 424]) ;
        DB::table('districts')->insert(['StCode' => 15,'DistrictName' => 'Rajauri','DistCode' => 425]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Rajkot','DistCode' => 426]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Rajsamand','DistCode' => 427]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Ramanathapuram','DistCode' => 428]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Rampur','DistCode' => 429]) ;
        DB::table('districts')->insert(['StCode' => 14,'DistrictName' => 'Rampur Bushahr','DistCode' => 430]) ;
        DB::table('districts')->insert(['StCode' => 16,'DistrictName' => 'Ranchi','DistCode' => 431]) ;
        DB::table('districts')->insert(['StCode' => 1,'DistrictName' => 'Rangat','DistCode' => 432]) ;
        DB::table('districts')->insert(['StCode' => 20,'DistrictName' => 'Ratlam','DistCode' => 433]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Ratnagiri','DistCode' => 434]) ;
        DB::table('districts')->insert(['StCode' => 15,'DistrictName' => 'Reasi','DistCode' => 435]) ;
        DB::table('districts')->insert(['StCode' => 20,'DistrictName' => 'Rewa','DistCode' => 436]) ;
        DB::table('districts')->insert(['StCode' => 23,'DistrictName' => 'Ri Bhoi','DistCode' => 437]) ;
        DB::table('districts')->insert(['StCode' => 13,'DistrictName' => 'Rohtak','DistCode' => 438]) ;
        DB::table('districts')->insert(['StCode' => 5,'DistrictName' => 'Rohtas','DistCode' => 439]) ;
        DB::table('districts')->insert(['StCode' => 28,'DistrictName' => 'Ropar','DistCode' => 440]) ;
        DB::table('districts')->insert(['StCode' => 35,'DistrictName' => 'Rudraprayag','DistCode' => 441]) ;
        DB::table('districts')->insert(['StCode' => 28,'DistrictName' => 'Rupnagar','DistCode' => 442]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Sabarkantha','DistCode' => 443]) ;
        DB::table('districts')->insert(['StCode' => 20,'DistrictName' => 'Sagar','DistCode' => 444]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Saharanpur','DistCode' => 445]) ;
        DB::table('districts')->insert(['StCode' => 5,'DistrictName' => 'Saharsa','DistCode' => 446]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Salem East','DistCode' => 447]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Salem West','DistCode' => 448]) ;
        DB::table('districts')->insert(['StCode' => 5,'DistrictName' => 'Samastipur','DistCode' => 449]) ;
        DB::table('districts')->insert(['StCode' => 26,'DistrictName' => 'Sambalpur','DistCode' => 450]) ;
        DB::table('districts')->insert(['StCode' => 32,'DistrictName' => 'Sangareddy','DistCode' => 451]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Sangli','DistCode' => 452]) ;
        DB::table('districts')->insert(['StCode' => 28,'DistrictName' => 'Sangrur','DistCode' => 453]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Sant Kabir Nagar','DistCode' => 454]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Sant Ravidas Nagar','DistCode' => 455]) ;
        DB::table('districts')->insert(['StCode' => 16,'DistrictName' => 'Santhal Parganas','DistCode' => 456]) ;
        DB::table('districts')->insert(['StCode' => 5,'DistrictName' => 'Saran','DistCode' => 457]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Satara','DistCode' => 458]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Sawai Madhopur','DistCode' => 459]) ;
        DB::table('districts')->insert(['StCode' => 32,'DistrictName' => 'Secunderabad','DistCode' => 460]) ;
        DB::table('districts')->insert(['StCode' => 20,'DistrictName' => 'Sehore','DistCode' => 461]) ;
        DB::table('districts')->insert(['StCode' => 22,'DistrictName' => 'Senapati','DistCode' => 462]) ;
        DB::table('districts')->insert(['StCode' => 24,'DistrictName' => 'Serchhip','DistCode' => 463]) ;
        DB::table('districts')->insert(['StCode' => 20,'DistrictName' => 'Shahdol','DistCode' => 464]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Shahjahanpur','DistCode' => 465]) ;
        DB::table('districts')->insert(['StCode' => 14,'DistrictName' => 'Shimla','DistCode' => 466]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Shimoga','DistCode' => 467]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Shrawasti','DistCode' => 468]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'Sibsagar','DistCode' => 469]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Siddharthnagar','DistCode' => 470]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Sikar','DistCode' => 471]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Sindhudurg','DistCode' => 472]) ;
        DB::table('districts')->insert(['StCode' => 16,'DistrictName' => 'Singhbhum','DistCode' => 473]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Sirohi','DistCode' => 474]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Sirsi','DistCode' => 475]) ;
        DB::table('districts')->insert(['StCode' => 5,'DistrictName' => 'Sitamarhi','DistCode' => 476]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Sitapur','DistCode' => 477]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Sivaganga','DistCode' => 478]) ;
        DB::table('districts')->insert(['StCode' => 5,'DistrictName' => 'Siwan','DistCode' => 479]) ;
        DB::table('districts')->insert(['StCode' => 14,'DistrictName' => 'Solan','DistCode' => 480]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Solapur','DistCode' => 481]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Sonbhadra','DistCode' => 482]) ;
        DB::table('districts')->insert(['StCode' => 13,'DistrictName' => 'Sonepat','DistCode' => 483]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'Sonitpur','DistCode' => 484]) ;
        DB::table('districts')->insert(['StCode' => 36,'DistrictName' => 'South 24 Parganas','DistCode' => 485]) ;
        DB::table('districts')->insert(['StCode' => 36,'DistrictName' => 'South Dinajpur','DistCode' => 486]) ;
        DB::table('districts')->insert(['StCode' => 23,'DistrictName' => 'South Garo Hills','DistCode' => 487]) ;
        DB::table('districts')->insert(['StCode' => 30,'DistrictName' => 'South Sikkim','DistCode' => 488]) ;
        DB::table('districts')->insert(['StCode' => 33,'DistrictName' => 'South Tripura','DistCode' => 489]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Srikakulam','DistCode' => 490]) ;
        DB::table('districts')->insert(['StCode' => 15,'DistrictName' => 'Srinagar','DistCode' => 491]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Srirangam','DistCode' => 492]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Sultanpur','DistCode' => 493]) ;
        DB::table('districts')->insert(['StCode' => 26,'DistrictName' => 'Sundargarh','DistCode' => 494]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Surat','DistCode' => 495]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Surendranagar','DistCode' => 496]) ;
        DB::table('districts')->insert(['StCode' => 32,'DistrictName' => 'Suryapet','DistCode' => 497]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Tadepalligudem','DistCode' => 498]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Tambaram','DistCode' => 499]) ;
        DB::table('districts')->insert(['StCode' => 22,'DistrictName' => 'Tamenglong','DistCode' => 500]) ;
        DB::table('districts')->insert(['StCode' => 36,'DistrictName' => 'Tamluk','DistCode' => 501]) ;
        DB::table('districts')->insert(['StCode' => 28,'DistrictName' => 'Tarn Taran','DistCode' => 502]) ;
        DB::table('districts')->insert(['StCode' => 3,'DistrictName' => 'Tawang','DistCode' => 503]) ;
        DB::table('districts')->insert(['StCode' => 35,'DistrictName' => 'Tehri Garhwal','DistCode' => 504]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Tenali','DistCode' => 505]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Thalassery','DistCode' => 506]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Thane','DistCode' => 507]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Thanjavur','DistCode' => 508]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Theni','DistCode' => 509]) ;
        DB::table('districts')->insert(['StCode' => 22,'DistrictName' => 'Thoubal','DistCode' => 510]) ;
        DB::table('districts')->insert(['StCode' => 4,'DistrictName' => 'Tinsukia','DistCode' => 511]) ;
        DB::table('districts')->insert(['StCode' => 3,'DistrictName' => 'Tirap','DistCode' => 512]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Tiruchirapalli','DistCode' => 513]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Tirunelveli','DistCode' => 514]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Tirupati','DistCode' => 515]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Tirupattur','DistCode' => 516]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Tirupur','DistCode' => 517]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Tirur','DistCode' => 518]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Tiruvalla','DistCode' => 519]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Tiruvannamalai','DistCode' => 520]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Tonk','DistCode' => 521]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Trichur','DistCode' => 522]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Trivandrum North','DistCode' => 523]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Trivandrum South','DistCode' => 524]) ;
        DB::table('districts')->insert(['StCode' => 25,'DistrictName' => 'Tuensang','DistCode' => 525]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Tumkur','DistCode' => 526]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Tuticorin','DistCode' => 527]) ;
        DB::table('districts')->insert(['StCode' => 29,'DistrictName' => 'Udaipur','DistCode' => 528]) ;
        DB::table('districts')->insert(['StCode' => 35,'DistrictName' => 'Udham Singh Nagar','DistCode' => 529]) ;
        DB::table('districts')->insert(['StCode' => 15,'DistrictName' => 'Udhampur','DistCode' => 530]) ;
        DB::table('districts')->insert(['StCode' => 17,'DistrictName' => 'Udupi','DistCode' => 531]) ;
        DB::table('districts')->insert(['StCode' => 20,'DistrictName' => 'Ujjain','DistCode' => 532]) ;
        DB::table('districts')->insert(['StCode' => 22,'DistrictName' => 'Ukhrul','DistCode' => 533]) ;
        DB::table('districts')->insert(['StCode' => 14,'DistrictName' => 'Una','DistCode' => 534]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Unnao','DistCode' => 535]) ;
        DB::table('districts')->insert(['StCode' => 3,'DistrictName' => 'Upper Siang','DistCode' => 536]) ;
        DB::table('districts')->insert(['StCode' => 3,'DistrictName' => 'Upper Subansiri','DistCode' => 537]) ;
        DB::table('districts')->insert(['StCode' => 35,'DistrictName' => 'Uttarkashi','DistCode' => 538]) ;
        DB::table('districts')->insert(['StCode' => 18,'DistrictName' => 'Vadakara','DistCode' => 539]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Vadodara East','DistCode' => 540]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Vadodara West','DistCode' => 541]) ;
        DB::table('districts')->insert(['StCode' => 5,'DistrictName' => 'Vaishali','DistCode' => 542]) ;
        DB::table('districts')->insert(['StCode' => 12,'DistrictName' => 'Valsad','DistCode' => 543]) ;
        DB::table('districts')->insert(['StCode' => 34,'DistrictName' => 'Varanasi','DistCode' => 544]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Vellore','DistCode' => 545]) ;
        DB::table('districts')->insert(['StCode' => 20,'DistrictName' => 'Vidisha','DistCode' => 546]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Vijayawada','DistCode' => 547]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Virudhunagar','DistCode' => 548]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Visakhapatnam','DistCode' => 549]) ;
        DB::table('districts')->insert(['StCode' => 2,'DistrictName' => 'Vizianagaram','DistCode' => 550]) ;
        DB::table('districts')->insert(['StCode' => 31,'DistrictName' => 'Vriddhachalam','DistCode' => 551]) ;
        DB::table('districts')->insert(['StCode' => 32,'DistrictName' => 'Wanaparthy','DistCode' => 552]) ;
        DB::table('districts')->insert(['StCode' => 32,'DistrictName' => 'Warangal','DistCode' => 553]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Wardha','DistCode' => 554]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Washim','DistCode' => 555]) ;
        DB::table('districts')->insert(['StCode' => 5,'DistrictName' => 'West Champaran','DistCode' => 556]) ;
        DB::table('districts')->insert(['StCode' => 23,'DistrictName' => 'West Garo Hills','DistCode' => 557]) ;
        DB::table('districts')->insert(['StCode' => 3,'DistrictName' => 'West Kameng','DistCode' => 558]) ;
        DB::table('districts')->insert(['StCode' => 23,'DistrictName' => 'West Khasi Hills','DistCode' => 559]) ;
        DB::table('districts')->insert(['StCode' => 3,'DistrictName' => 'West Siang','DistCode' => 560]) ;
        DB::table('districts')->insert(['StCode' => 30,'DistrictName' => 'West Sikkim','DistCode' => 561]) ;
        DB::table('districts')->insert(['StCode' => 33,'DistrictName' => 'West Tripura','DistCode' => 562]) ;
        DB::table('districts')->insert(['StCode' => 25,'DistrictName' => 'Wokha','DistCode' => 563]) ;
        DB::table('districts')->insert(['StCode' => 21,'DistrictName' => 'Yavatmal','DistCode' => 564]) ;
        DB::table('districts')->insert(['StCode' => 25,'DistrictName' => 'Zunhebotto','DistCode' => 565]) ;
    }
}
